### ISSUE TITLE
unable to copy course due to syntax issue in module

### ISSUE THREAD

**Issue by adamfortman** [richardjonesnz/moodle-mod_simplelesson#2]
When attempting to copy a course, the following error is displayed:

> Exception - syntax error, unexpected single-quoted string "simplelessonid", expecting ")"

The syntax error is located in this file and here is the fix:

```
[root@vm2 ~]# diff /home/devmoodle/public_html/mod/simplelesson/backup/moodle2/backup_simplelesson_stepslib.php{,.bak}
71c71
<                 ['simplelessonid', 'qubaid', 'userid', 'status',
---
>                 []'simplelessonid', 'qubaid', 'userid', 'status',
```

Removing the `]` from near the beginning of the array allows a course to be copied.

**Comment by richardjonesnz** [comment]
Thank you Adam, looks like a simple syntax error but will check why it didn't show up in my editor.  Could you please confirm Moodle version and simplelesson version being used here.  Many thanks, Richard.

**Comment by adamfortman** [comment]
Ah, yeah, sorry about that!

Moodle: 4.4 Build: 20240516
mod_simplelesson: v2.06. 2024020601

**Comment by richardjonesnz** [comment]
Thanks again Adam, should be all ok now.
